### ISSUE TITLE
Publish superagent-prefix to NPM?

### ISSUE THREAD

**Issue by kadamwhite** [johntron/superagent-prefix#1]
[superagent](https://github.com/visionmedia/superagent) is available through NPM; however, this module is only available using composer. If it is possible to publish `superagent-prefix` to NPM as well, it could be required alongside superagent itself—at the moment it needs to be separately downloaded and saved into the repository rather than just declaring it as an NPM module dependency.

No pressure if you'd prefer not to, just a suggestion. Thanks!

**Comment by brentertz** [comment]
:+1:

**Comment by mattahorton** [comment]
+1

**Comment by mattahorton** [comment]
Seeing as the project was under the MIT license, I forked and published this on NPM.

https://www.npmjs.org/package/superagent-prefix

**Comment by dustinlarimer** [comment]
you rock, thanks @mattahorton :+1:

**Comment by johntron** [comment]
Thanks @mattahorton @kadamwhite! sorry I missed the notification from original PR.

**Comment by mattahorton** [comment]
@dustinlarimer @johntron forgot I did this. Glad you all found it useful.
